import datetime
import pickle
import random


def generate_titles():
    x = ["Dream", "Dreamer", "Dreams", "Waves",
         "Sword", "Kiss", "Sex", "Lover",
         "Slave", "Slaves", "Pleasure", "Servant",
         "Servants", "Snake", "Soul", "Touch",
         "Men", "Women", "Gift", "Scent",
         "Ice", "Snow", "Night", "Silk", "Secret", "Secrets",
         "Game", "Fire", "Flame", "Flames",
         "Husband", "Wife", "Man", "Woman", "Boy", "Girl",
         "Truth", "Edge", "Boyfriend", "Girlfriend",
         "Body", "Captive", "Male", "Wave", "Predator",
         "Female", "Healer", "Trainer", "Teacher",
         "Hunter", "Obsession", "Hustler", "Consort",
         "Dream", "Dreamer", "Dreams", "Rainbow",
         "Dreaming", "Flight", "Flying", "Soaring",
         "Wings", "Mist", "Sky", "Wind",
         "Winter", "Misty", "River", "Door",
         "Gate", "Cloud", "Fairy", "Dragon",
         "End", "Blade", "Beginning", "Tale",
         "Tales", "Emperor", "Prince", "Princess",
         "Willow", "Birch", "Petals", "Destiny",
         "Theft", "Thief", "Legend", "Prophecy",
         "Spark", "Sparks", "Stream", "Streams", "Waves",
         "Sword", "Darkness", "Swords", "Silence", "Kiss",
         "Butterfly", "Shadow", "Ring", "Rings", "Emerald",
         "Storm", "Storms", "Mists", "World", "Worlds",
         "Alien", "Lord", "Lords", "Ship", "Ships", "Star",
         "Stars", "Force", "Visions", "Vision", "Magic",
         "Wizards", "Wizard", "Heart", "Heat", "Twins",
         "Twilight", "Moon", "Moons", "Planet", "Shores",
         "Pirates", "Courage", "Time", "Academy",
         "School", "Rose", "Roses", "Stone", "Stones",
         "Sorcerer", "Shard", "Shards", "Slave", "Slaves",
         "Servant", "Servants", "Serpent", "Serpents",
         "Snake", "Soul", "Souls", "Savior", "Spirit",
         "Spirits", "Voyage", "Voyages", "Voyager", "Voyagers",
         "Return", "Legacy", "Birth", "Healer", "Healing",
         "Year", "Years", "Death", "Dying", "Luck", "Elves",
         "Tears", "Touch", "Son", "Sons", "Child", "Children",
         "Illusion", "Sliver", "Destruction", "Crying", "Weeping",
         "Gift", "Word", "Words", "Thought", "Thoughts", "Scent",
         "Ice", "Snow", "Night", "Silk", "Guardian", "Angel",
         "Angels", "Secret", "Secrets", "Search", "Eye", "Eyes",
         "Danger", "Game", "Fire", "Flame", "Flames", "Bride",
         "Husband", "Wife", "Time", "Flower", "Flowers",
         "Light", "Lights", "Door", "Doors", "Window", "Windows",
         "Bridge", "Bridges", "Ashes", "Memory", "Thorn",
         "Thorns", "Name", "Names", "Future", "Past",
         "History", "Something", "Nothing", "Someone",
         "Nobody", "Person", "Man", "Woman", "Boy", "Girl",
         "Way", "Mage", "Witch", "Witches", "Lover",
         "Tower", "Valley", "Abyss", "Hunter",
         "Truth", "Edge"]

    y = ["Lost", "Only", "Last", "First",
         "Third", "Sacred", "Bold", "Lovely",
         "Final", "Missing", "Shadowy", "Seventh",
         "Dwindling", "Missing", "Absent",
         "Vacant", "Cold", "Hot", "Burning", "Forgotten",
         "Weeping", "Dying", "Lonely", "Silent",
         "Laughing", "Whispering", "Forgotten", "Smooth",
         "Silken", "Rough", "Frozen", "Wild",
         "Trembling", "Fallen", "Ragged", "Broken",
         "Cracked", "Splintered", "Slithering", "Silky",
         "Wet", "Magnificent", "Luscious", "Swollen",
         "Erect", "Bare", "Naked", "Stripped",
         "Captured", "Stolen", "Sucking", "Licking",
         "Growing", "Kissing", "Green", "Red", "Blue",
         "Azure", "Rising", "Falling", "Elemental",
         "Bound", "Prized", "Obsessed", "Unwilling",
         "Hard", "Eager", "Ravaged", "Sleeping",
         "Wanton", "Professional", "Willing", "Devoted",
         "Misty", "Lost", "Only", "Last", "First",
         "Final", "Missing", "Shadowy", "Seventh",
         "Dark", "Darkest", "Silver", "Silvery", "Living",
         "Black", "White", "Hidden", "Entwined", "Invisible",
         "Next", "Seventh", "Red", "Green", "Blue",
         "Purple", "Grey", "Bloody", "Emerald", "Diamond",
         "Frozen", "Sharp", "Delicious", "Dangerous",
         "Deep", "Twinkling", "Dwindling", "Missing", "Absent",
         "Vacant", "Cold", "Hot", "Burning", "Forgotten",
         "Some", "No", "All", "Every", "Each", "Which", "What",
         "Playful", "Silent", "Weeping", "Dying", "Lonely", "Silent",
         "Laughing", "Whispering", "Forgotten", "Smooth", "Silken",
         "Rough", "Frozen", "Wild", "Trembling", "Fallen",
         "Ragged", "Broken", "Cracked", "Splintered"]

    items = set(
        random.choice(x) + ' ' + random.choice(y) for i in range(10000))


def generate_words():
    words = open('words_eng').read().splitlines()

    items = set(
        ' '.join(random.choices(words, k=random.randint(1, 1000))) for i in
        range(10_000))


def generate_datas():
    items = set(datetime.datetime(year=random.randint(1979, 2022),
                                  month=random.randint(1, 12),
                                  day=random.randint(1, 28),
                                  hour=random.randint(1, 23),
                                  minute=random.randint(1, 59)) for i in
                range(10_000))


def get_random_links():
    words = ["account", "achiever", "acoustics", "act", "action", "activity",
             "actor", "addition", "adjustment", "advertisement", "advice",
             "aftermath", "afternoon", "afterthought", "agreement", "air",
             "airplane", "airport", "alarm", "amount", "amusement", "anger",
             "angle", "animal", "ants", "apparatus", "apparel", "appliance",
             "approval", "arch", "argument", "arithmetic", "arm", "army",
             "art",
             "attack", "attraction", "aunt", "authority", "babies", "baby",
             "back", "badge", "bag", "bait", "balance", "ball", "base",
             "baseball", "basin", "basket", "basketball", "bat", "bath",
             "battle",
             "bead", "bear", "bed", "bedroom", "beds", "bee", "beef",
             "beginner",
             "behavior", "belief", "believe", "bell", "bells", "berry", "bike",
             "bikes", "bird", "birds", "birth", "birthday", "bit", "bite",
             "blade", "blood", "blow", "board", "boat", "bomb", "bone", "book",
             "books", "boot", "border", "bottle", "boundary", "box", "boy",
             "brake", "branch", "brass", "breath", "brick", "bridge",
             "brother",
             "bubble", "bucket", "building", "bulb", "burst", "bushes",
             "business", "butter", "button", "cabbage", "cable", "cactus",
             "cake",
             "cakes", "calculator", "calendar", "camera", "camp", "can",
             "cannon",
             "canvas", "cap", "caption", "car", "card", "care", "carpenter",
             "carriage", "cars", "cart", "cast", "cat", "cats", "cattle",
             "cause",
             "cave", "celery", "cellar", "cemetery", "cent", "chalk", "chance",
             "change", "channel", "cheese", "cherries", "cherry", "chess",
             "chicken", "chickens", "children", "chin", "church", "circle",
             "clam", "class", "cloth", "clover", "club", "coach", "coal",
             "coast",
             "coat", "cobweb", "coil", "collar", "color", "committee",
             "company",
             "comparison", "competition", "condition", "connection", "control",
             "cook", "copper", "corn", "cough", "country", "cover", "cow",
             "cows",
             "crack", "cracker", "crate", "crayon", "cream", "creator",
             "creature", "credit", "crib", "crime", "crook", "crow", "crowd",
             "crown", "cub", "cup", "current", "curtain", "curve", "cushion",
             "dad", "daughter", "day", "death", "debt", "decision", "deer",
             "degree", "design", "desire", "desk", "destruction", "detail",
             "development", "digestion", "dime", "dinner", "dinosaurs",
             "direction", "dirt", "discovery", "discussion", "distance",
             "distribution", "division", "dock", "doctor", "dog", "dogs",
             "doll",
             "dolls", "donkey", "door", "downtown", "drain", "drawer", "dress",
             "drink", "driving", "drop", "duck", "ducks", "dust", "ear",
             "earth",
             "earthquake", "edge", "education", "effect", "egg", "eggnog",
             "eggs",
             "elbow", "end", "engine", "error", "event", "example", "exchange",
             "existence", "expansion", "experience", "expert", "eye", "eyes",
             "face", "fact", "fairies", "fall", "fang", "farm", "fear",
             "feeling",
             "field", "finger", "fire", "fireman", "fish", "flag", "flame",
             "flavor", "flesh", "flight", "flock", "floor", "flower",
             "flowers",
             "fly", "fog", "fold", "food", "foot", "force", "fork", "form",
             "fowl", "frame", "friction", "friend", "friends", "frog", "frogs",
             "front", "fruit", "fuel", "furniture", "gate", "geese", "ghost",
             "giants", "giraffe", "girl", "girls", "glass", "glove", "gold",
             "government", "governor", "grade", "grain", "grandfather",
             "grandmother", "grape", "grass", "grip", "ground", "group",
             "growth",
             "guide", "guitar", "gun", "hair", "haircut", "hall", "hammer",
             "hand", "hands", "harbor", "harmony", "hat", "hate", "head",
             "health", "heat", "hill", "history", "hobbies", "hole", "holiday",
             "home", "honey", "hook", "hope", "horn", "horse", "horses",
             "hose",
             "hospital", "hot", "hour", "house", "houses", "humor", "hydrant",
             "ice", "icicle", "idea", "impulse", "income", "increase",
             "industry",
             "ink", "insect", "instrument", "insurance", "interest",
             "invention",
             "iron", "island", "jail", "jam", "jar", "jeans", "jelly",
             "jellyfish", "jewel", "join", "judge", "juice", "jump", "kettle",
             "key", "kick", "kiss", "kittens", "kitty", "knee", "knife",
             "knot",
             "knowledge", "laborer", "lace", "ladybug", "lake", "lamp", "land",
             "language", "laugh", "leather", "leg", "legs", "letter",
             "letters",
             "lettuce", "level", "library", "limit", "line", "linen", "lip",
             "liquid", "loaf", "lock", "locket", "look", "loss", "love", "low",
             "lumber", "lunch", "lunchroom", "machine", "magic", "maid",
             "mailbox", "man", "marble", "mark", "market", "mask", "mass",
             "match", "meal", "measure", "meat", "meeting", "memory", "men",
             "metal", "mice", "middle", "milk", "mind", "mine", "minister",
             "mint", "minute", "mist", "mitten", "mom", "money", "monkey",
             "month", "moon", "morning", "mother", "motion", "mountain",
             "mouth",
             "move", "muscle", "name", "nation", "neck", "need", "needle",
             "nerve", "nest", "night", "noise", "north", "nose", "note",
             "notebook", "number", "nut", "oatmeal", "observation", "ocean",
             "offer", "office", "oil", "orange", "oranges", "order", "oven",
             "page", "pail", "pan", "pancake", "paper", "parcel", "part",
             "partner", "party", "passenger", "payment", "peace", "pear",
             "pen",
             "pencil", "person", "pest", "pet", "pets", "pickle", "picture",
             "pie", "pies", "pig", "pigs", "pin", "pipe", "pizzas", "place",
             "plane", "planes", "plant", "plantation", "plants", "plastic",
             "plate", "play", "playground", "pleasure", "plot", "plough",
             "pocket", "point", "poison", "pollution", "popcorn", "porter",
             "position", "pot", "potato", "powder", "power", "price",
             "produce",
             "profit", "property", "prose", "protest", "pull", "pump",
             "punishment", "purpose", "push", "quarter", "quartz", "queen",
             "question", "quicksand", "quiet", "quill", "quilt", "quince",
             "quiver", "rabbit", "rabbits", "rail", "railway", "rain",
             "rainstorm", "rake", "range", "rat", "rate", "ray", "reaction",
             "reading", "reason", "receipt", "recess", "record", "regret",
             "relation", "religion", "representative", "request", "respect",
             "rest", "reward", "rhythm", "rice", "riddle", "rifle", "ring",
             "rings", "river", "road", "robin", "rock", "rod", "roll", "roof",
             "room", "root", "rose", "route", "rub", "rule", "run", "sack",
             "sail", "salt", "sand", "scale", "scarecrow", "scarf", "scene",
             "scent", "school", "science", "scissors", "screw", "sea",
             "seashore",
             "seat", "secretary", "seed", "selection", "self", "sense",
             "servant",
             "shade", "shake", "shame", "shape", "sheep", "sheet", "shelf",
             "ship", "shirt", "shock", "shoe", "shoes", "shop", "show", "side",
             "sidewalk", "sign", "silk", "silver", "sink", "sister", "sisters",
             "size", "skate", "skin", "skirt", "sky", "slave", "sleep",
             "sleet",
             "slip", "slope", "smash", "smell", "smile", "smoke", "snail",
             "snails", "snake", "snakes", "sneeze", "snow", "soap", "society",
             "sock", "soda", "sofa", "son", "song", "songs", "sort", "sound",
             "soup", "space", "spade", "spark", "spiders", "sponge", "spoon",
             "spot", "spring", "spy", "square", "squirrel", "stage", "stamp",
             "star", "start", "statement", "station", "steam", "steel", "stem",
             "step", "stew", "stick", "sticks", "stitch", "stocking",
             "stomach",
             "stone", "stop", "store", "story", "stove", "stranger", "straw",
             "stream", "street", "stretch", "string", "structure", "substance",
             "sugar", "suggestion", "suit", "summer", "sun", "support",
             "surprise", "sweater", "swim", "swing", "system", "table", "tail",
             "talk", "tank", "taste", "tax", "teaching", "team", "teeth",
             "temper", "tendency", "tent", "territory", "test", "texture",
             "theory", "thing", "things", "thought", "thread", "thrill",
             "throat",
             "throne", "thumb", "thunder", "ticket", "tiger", "time", "tin",
             "title", "toad", "toe", "toes", "tomatoes", "tongue", "tooth",
             "toothbrush", "toothpaste", "top", "touch", "town", "toy", "toys",
             "trade", "trail", "train", "trains", "tramp", "transport", "tray",
             "treatment", "tree", "trees", "trick", "trip", "trouble",
             "trousers",
             "truck", "trucks", "tub", "turkey", "turn", "twig", "twist",
             "umbrella", "uncle", "underwear", "unit", "use", "vacation",
             "value",
             "van", "vase", "vegetable", "veil", "vein", "verse", "vessel",
             "vest", "view", "visitor", "voice", "volcano", "volleyball",
             "voyage", "walk", "wall", "war", "wash", "waste", "watch",
             "water",
             "wave", "waves", "wax", "way", "wealth", "weather", "week",
             "weight",
             "wheel", "whip", "whistle", "wilderness", "wind", "window",
             "wine",
             "wing", "winter", "wire", "wish", "woman", "women", "wood",
             "wool",
             "word", "work", "worm", "wound", "wren", "wrench", "wrist",
             "writer",
             "writing", "yak", "yam", "yard", "yarn", "year", "yoke", "zebra",
             "zephyr", "zinc", "zipper", "zoo"]
    items = set(
        f'https://{random.choice(words)}.{random.choice(words)}.com' for i in
        range(5000))


def dump(items):
    pickle.dump(items, open('urls_pickle.txt', 'wb'))


def load():
    pickle.load(open('urls_pickle.txt', 'rb'))
